// Define navigation params
export type RootStackParamList = {
  Auth: undefined;
  Login: undefined;
  Email: undefined;
  Name: { userId: number };
  Password: { userId: number };
  About: { userId: number };
  SocialMedia: undefined;
  AccountCreated: undefined;
  Home: undefined;
  CampaignDetail: undefined;
  AudienceStats: undefined;
  CampaignIdeaScreen: undefined;
  Profile: undefined;
  Notifications: undefined;
  PersonalInfo: undefined;
  SocialMediaProfile: undefined;
  Messages: undefined;
  MessageDetail: { messageId: string; brand: string };
  AddPaymentMethod: undefined;
  Paypal: undefined;
  PaymentMethods: undefined;
  MyCampaigns: undefined;
  EditName: undefined;
  EditEmail: undefined;
  EditPassword: undefined;
  EditPersonalData: { section?: 'gender' | 'birthdate' | 'location' } | undefined;
  EditPhone: undefined;
};
